### ISSUE TITLE
isResolved should be named isFulfilled

### ISSUE THREAD

**Issue by julien-f** [thejameskyle/proposal-promise-access-internal-fields#1]
AFAIU, resolved means that the promise is fulfilled (has a value) or is chained to another promise (which might not be settled).

**Comment by iamstarkov** [comment]
afaik, `isFullfilled = (isResolved || isRejected)`

**Comment by julien-f** [comment]
Nope, that's (almost) *settled*.

`isSettled = isFulfilled || isRejected`

~~And in fact, resolved is even an alias for settled ([source](https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md#fates)).~~

`isResolved = isSettled || isChainedToOtherPromise`

**Comment by iamstarkov** [comment]
you are right
![screen shot 2017-03-10 at 12 31 33](https://cloud.githubusercontent.com/assets/559321/23793840/89391264-058d-11e7-921d-b17b381d0143.png)

**Comment by jamiebuilds** [comment]
We don't currently expose the word `fulfilled` anywhere in the Promise api. `Promise.resolve` is exposed though.

**Comment by ljharb** [comment]
That difference is because resolving is a verb that can include resolving to another promise's state - although I prefer the term "resolve" here, "fulfill" is indeed correct. This has its roots in E's promises.

The spec's intention was for the new Promise executor's arguments to be named "fulfill, reject" - altho the community tends to call them "resolve, reject".

**Comment by jamiebuilds** [comment]
My point was that the name of the argument is not exposed as either `fulfill` or `reject`. The only place a name is exposed is `Promise.resolve` and I would rather match that naming.

**Comment by ljharb** [comment]
Right, but "is resolved" doesn't mean the same thing as "is fulfilled", and `Promise.resolve` does *not* guarantee you get a fulfilled promise - `Promise.resolve(pendingPromise)` gives you a pending promise. Thus "is resolved" isn't actually useful, since all that tells you is that the Promise's state is either fulfilled, rejected, or *delegated* to another Promise. "is fulfilled" is what tells you that it is irrevocably settled with a non-rejection.

**Comment by domenic** [comment]
https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md

**Comment by domenic** [comment]
> The spec's intention was for the new Promise executor's arguments to be named "fulfill, reject" - altho the community tends to call them "resolve, reject".

False. The resolve() argument resolves, not fulfills, e.g. try `resolve(Promise.reject(new Error()))`.

**Comment by ljharb** [comment]
Oops, you are indeed correct. Is the rest of my statement still accurate?

**Comment by domenic** [comment]
Yeah

**Comment by jamiebuilds** [comment]
Changed api and used fulfilled
